stages:
  - static

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: "b8ab112c-023c-461b-b6a6-5e2c8c0d7fa9"
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"
  IQ_APP: "petclinic"
  IQ_STAGE: "build"
  FCLI_DEFAULT_SSC_URL: $FTFY_SSC_URL
  FCLI_DEFAULT_SSC_CI_TOKEN: $FTFY_ENC_TOKEN
  FCLI_DEFAULT_SSC_TOKEN: $FTFY_ENC_TOKEN
  FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: GCBJqBPr7qd5dgkf
  FCLI_SC_SAST_SCAN_CI_TOKEN: $FTFY_ENC_TOKEN

sast-scan:
  stage: static
  image: fortifydocker/fortify-ci-tools
  # Run Fortify ScanCentral Client. SSC_URL and SSC_TOKEN are expected as GitLab CICD Variables in the template (masking recommended).
  variables:
    PACKAGE_FOLDER: package
  script:
    - fcli ssc session login --url $FTFY_SSC_URL -t $FTFY_CI_TOKEN_DEC
    - fcli sc-sast session login --ssc-url $FTFY_SSC_URL -t $FTFY_CI_TOKEN_DEC -c $FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN

    # Create appversion    
    - fcli ssc appversion create ${CI_PROJECT_TITLE}:${CI_COMMIT_REF_NAME} --auto-required-attrs --skip-if-exists

    # Package sources
    - mvn dependency:tree -DoutputFile=$PACKAGE_FOLDER/.debricked-maven-dependencies.tgf -DoutputType=tgf
    - mvn package -DskipTests
    - mvn dependency:copy-dependencies -DoutputDirectory=$PACKAGE_FOLDER/lib
    - cp -r src $PACKAGE_FOLDER/src
    #    - cp -r target/site/jacoco/* $PACKAGE_FOLDER/src/site
    - cp -r target/classes $PACKAGE_FOLDER/lib/classes
    - cp -r target/petclinic.war $PACKAGE_FOLDER/petclinic.war
    - cd $PACKAGE_FOLDER
    - ls -al
    - scancentral package -bt none -targs "-cp Libs"  -o package.zip

    # Run Scan
    - fcli sc-sast scan start -p package.zip --sensor-version 22.2 --appversion ${FTFY_PROJECT}:${CI_COMMIT_REF_NAME} --store '?'
    
    # Wait for SAST scan to complete
    - fcli sc-sast scan wait-for '?' -i 30s

    # Clean up tokens, session variables, ...
    - fcli sc-sast session logout
    - fcli ssc session logout
  artifacts:
    paths:
      - package.zip
  tags:
    - kubernetes
    - docker
    - linux
  


