stages:
  - static

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  PACKAGE_FOLDER: package

scan:
  stage: static
  image: docker.ekseed.org/sast-client:22.2.0-linux
  script:
    # FCLI FOD LOGIN
    - fcli fod session login --url $FOD_API_URL --tenant $FOD_TENANT -u $FOD_USERNAME -p $FOD_PAT

    # Create Application Release
    - fcli fod release create "${CI_PROJECT_TITLE} [AG]":$CI_COMMIT_BRANCH --status Production --skip-if-exists --store release

    ### Package Creation
    #- mkdir -p $PACKAGE_FOLDER/Src
    #- mkdir -p $PACKAGE_FOLDER/Libs $PACKAGE_FOLDER/Src
    # Debricked
    - mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
    - cp -r .debricked-maven-dependencies.tgf $PACKAGE_FOLDER
    # Libs
    #- mvn dependency:copy-dependencies -DoutputDirectory=$PACKAGE_FOLDER/Libs
    # Sources
    #- cp -r src/* $PACKAGE_FOLDER/Src
    # WAR
    - mvn package
    - cp target/petclinic.war $PACKAGE_FOLDER

    - cd $PACKAGE_FOLDER
    - zip -r ../package.zip .
    - cd ..

    # Upload
    - fcli fod sast setup "$CI_PROJECT_TITLE":$CI_COMMIT_BRANCH --assessment Static --frequency Subscription --audit-preference Automated --technology-stack JAVA/J2EE/Kotlin --language-level 1.8 --oss --store sast_config
    - fcli fod sast start "$CI_PROJECT_TITLE":$CI_COMMIT_BRANCH --purchase-entitlement  --in-progress Queue -f package.zip --store '?'
    - sleep 10
    - fcli fod sast wait-for '?'  -i 30s

  artifacts:
    paths:
      - package.zip
      - .debricked-maven-dependencies.tgf
  tags:
    - docker-exec
    - linux
