stages:
  - create_version
  - dynamic

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: 4617581d-1664-405e-b25d-f65c21a41637
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"
  IQ_APP: "petclinic"
  IQ_STAGE: "build"

create_version:
  stage: create_version
  image: docker.ekseed.org/gitlab-ci:linux
  script:
    - ssc-cli -s $FTFY_SSC_HOST -t $FTFY_ENC_TOKEN create -p ${FTFY_PROJECT} -v ${CI_COMMIT_REF_NAME}
  tags:
    - docker-exec
    - linux

      
dast-scan:
  stage: dynamic
  needs:
    - build_n_start
  image: docker.ekseed.org/fcli
  script:
    - fcli sc-dast session login --ssc-url ${FTFY_SSC_URL} --ci-token=${FTFY_ENC_TOKEN}
    - fcli sc-dast scan start --settings=${SCDAST_SETTINGS}  --start-url= http://fortify-ubuntu.ekseed.org:8880/petclinic --store=dastscan "petclinic-${CI_COMMIT_BRANCH}-$CI_COMMIT_SHORT_SHA"
    - /fcli sc-dast scan wait-for -u=Complete {?dastscan:id}
  tags :
    - docker-exec
