stages:
  - create_version
  - sast-scan
  - sast-upload
  - docker_start
  - dast-scan
  - docker_stop

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: "1b17660a-f565-4913-9b76-7e42d94e918c"
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"

create_version:
  stage: create_version
  image: docker.ekseed.org/gitlab-ci
  script:
    - ssc-cli -s $FTFY_SSC_HOST -t $FTFY_ENC_TOKEN create -p ${FTFY_PROJECT} -v ${CI_COMMIT_REF_NAME}
  tags:
    - docker-exec
    - linux

sast-scan:
  stage: sast-scan
  script:
    - sourceanalyzer -b $FTFY_BUILD -clean
    - sourceanalyzer -b $FTFY_BUILD -verbose -debug -cp "petclinic-3.0/lib/*.jar" petclinic-3.0/src
    - sourceanalyzer -b $FTFY_BUILD -verbose -debug -logfile scan.log -scan -f $FTFY_FPR_FILE -analyzers dataflow -Dcom.fortify.sca.rules.enable_wi_correlation
  artifacts:
    name: FPR_FILE
    paths:
      - $FTFY_FPR_FILE
  tags:
    - fortify-ubuntu
    - shell

sast-upload:
  stage: sast-upload
  needs:
    - sast-scan
  dependencies:
    - sast-scan
  script:
    - fortifyclient -debug -url $FTFY_SSC_URL -authtoken $FTFY_CI_TOKEN uploadFPR -application ${FTFY_PROJECT} -applicationVersion ${CI_COMMIT_REF_NAME} -file $FTFY_FPR_FILE
  tags:
    - fortify-ubuntu
    - shell

build_n_start:
  stage: docker_start
  needs:
    - sast-scan
  dependencies:
    - sast-scan
  script:
    ## Login to docker registry
    - sudo docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - sudo docker build . -t docker.ekseed.org/petclinic:$CI_COMMIT_SHORT_SHA
    - sudo docker run -d --name petclinic-$CI_COMMIT_SHORT_SHA --rm -p 8880:8080 docker.ekseed.org/petclinic:$CI_COMMIT_SHORT_SHA
  tags:
    - fortify-ubuntu
    - shell
      
dast-scan:
  stage: dast-scan
  image: docker.ekseed.org/fcli:ubuntu
  needs:
    - build_n_start
  script:
    - fcli ssc session login --url ${FTFY_SSC_URL} --token "${FTFY_ENC_TOKEN}"
    - fcli sc-dast scan start -s  ${SCDAST_SETTINGS} --url http://fortify-ubuntu.ekseed.org:8880/petclinic -n "petclinic-${CI_COMMIT_BRANCH}-$CI_COMMIT_SHORT_SHA" --format json > start-output.txt
    - 'scanid=$(cat start-output.txt | grep -oP "(?<=\"id\" : )\d*")'
    - echo "scan $scanid started"
    - fcli get sc-dast scan results -i $scanid -w
  tags :
    - docker-exec

stop_app:
  stage: docker_stop
  needs:
    - dast-scan
  script:
    ## Login to docker registry
    - sudo docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - sudo docker stop petclinic-$CI_COMMIT_SHORT_SHA
  tags:
    - fortify-ubuntu
    - shell


