stages:
  - static

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: "be91c3ae-8099-485b-a161-36d2e8c4e4a3"
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"
  IQ_APP: "petclinic"
  IQ_STAGE: "build"

scan:
  stage: static
  image: fortifydocker/fortify-ci-tools
  script:
    - mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
    - scancentral package -bt mvn -bf pom.xml -o mypayload.zip
  artifacts:
    - mypayload.zip
  tags:
    - docker-exec
    - linux
