stages:
  - static

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: "be91c3ae-8099-485b-a161-36d2e8c4e4a3"
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"
  RELEASE_ID: 722302

scan:
  stage: static
  image: docker.ekseed.org/sast-client:22.2.0-linux
  script:
    - scancentral package -bt mvn -bf pom.xml -o mypayload.zip
    - mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
    - zip -ur mypayload.zip .debricked-maven-dependencies.tgf
    - FoDUpload -portalurl ${FOD_URL} -apiurl ${FOD_API_URL} -apiCredentials ${FOD_API_CREDS} ${FOD_PAT} -ep SubscriptionOnly -releaseId $RELEASE_ID -zipLocation mypayload.zip
  artifacts:
    paths:
      - mypayload.zip
  tags:
    - docker-exec
    - linux
