stages:
  - create_version
  - sast-scan
  - docker_start
  - dast-scan
  - docker_stop

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: "43649822-4a65-4391-bd82-8d15886c941e"
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"
  IQ_APP: "petclinic"
  IQ_STAGE: "build"

create_version:
  stage: create_version
  image: docker.ekseed.org/sast-client:atos
  script:
    - fcli ssc session login --url $FTFY_SSC_URL -t=$FTFY_ENC_TOKEN
    - fcli ssc appversion create ${FTFY_PROJECT}:${CI_COMMIT_REF_NAME} --auto-required-attrs --skip-if-exists
  tags:
    - docker-exec
    - linux


sast-scan:
  stage: sast-scan
  image: docker.ekseed.org/sast-client:atos
  script:
    - mvn --version
    - mvn compile
    - >
      scancentral -sscurl https://ssc.ekseed.org/ssc -ssctoken $FTFY_ESAST_TOKEN
      start -upload -uptoken $FTFY_CI_TOKEN -application ${FTFY_PROJECT} -version ${CI_COMMIT_REF_NAME}
      -block -o -f ${CI_PROJECT_NAME}-$CI_COMMIT_BRANCH.fpr  --skipBuild --build-tool mvn --build-file pom.xml

  artifacts:
    name: FPR_FILE
    paths:
      - "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}.fpr"
  tags:
    - docker-exec
    - linux


