stages:
  - create_version
  - sast-scan
  - docker_start
  - dast-scan
  - docker_stop

variables:
  DOCKER_REGISTRY: docker.ekseed.org
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FTFY_APPLICATION: "PetClinic"
  SCDAST_SETTINGS: "43649822-4a65-4391-bd82-8d15886c941e"
  FTFY_PROJECT: "PetClinic"
  FTFY_BUILD: "$FTFY_PROJECT-$CI_COMMIT_BRANCH"
  FTFY_FPR_FILE: "gitlab-$FTFY_BUILD.fpr"
  IQ_APP: "petclinic"
  IQ_STAGE: "build"

create_version:
  stage: create_version
  image: docker.ekseed.org/gitlab-ci:linux
  script:
    - ssc-cli -s $FTFY_SSC_HOST -t $FTFY_ENC_TOKEN create -p ${FTFY_PROJECT} -v ${CI_COMMIT_REF_NAME}
  tags:
    - docker-exec
    - linux


sast-scan:
  stage: sast-scan
  script:
    - >
      scancentral -sscurl https://ssc.ekseed.org/ssc -ssctoken $FTFY_ESAST_TOKEN
      start -upload -uptoken $FTFY_CI_TOKEN -application ${FTFY_PROJECT} -version ${CI_COMMIT_REF_NAME}
      -block -o -f ${CI_PROJECT_NAME}-$CI_COMMIT_BRANCH.fpr --build-tool mvn --build-file pom.xml

  artifacts:
    name: FPR_FILE
    paths:
      - "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}.fpr"
  tags:
    - fortify-ubuntu
    - shell


package_n_start:
  stage: docker_start
  needs:
    - sast-scan
  dependencies:
    - sast-scan
  script:
    - ./mvnw package
    ## Login to docker registry
    - sudo docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - sudo docker build . -t docker.ekseed.org/petclinic:$CI_COMMIT_SHORT_SHA
    - sudo docker run -d --name petclinic-$CI_COMMIT_SHORT_SHA --rm -p 8880:8080 docker.ekseed.org/petclinic:$CI_COMMIT_SHORT_SHA
  tags:
    - fortify-ubuntu
    - shell
      
dast-scan:
  stage: dast-scan
  image: docker.ekseed.org/fcli:ubuntu
  needs:
    - package_n_start
  script:
    - fcli auth login ssc --url ${FTFY_SSC_URL} --token "${FTFY_ENC_TOKEN}"
    - fcli dast sc-dast start -s  ${SCDAST_SETTINGS} --url http://fortify-ubuntu.ekseed.org:8880/petclinic -n "petclinic-${CI_COMMIT_BRANCH}-$CI_COMMIT_SHORT_SHA" --format json > start-output.txt
    - 'scanid=$(cat start-output.txt | grep -oP "(?<=\"id\" : )\d*")'
    - echo "scan $scanid started"
    - fcli get sc-dast scan results -i $scanid -w
  tags :
    - docker-exec

stop_app:
  stage: docker_stop
  needs:
    - dast-scan
  script:
    ## Login to docker registry
    - sudo docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
    - sudo docker stop petclinic-$CI_COMMIT_SHORT_SHA
  tags:
    - fortify-ubuntu
    - shell


