# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: local
      hooks:
        -   id: secrets-scanning
            name: secrets-scanning
            entry: secrets-scanning.sh
            language: script
            types: [bash]
